### ISSUE TITLE
CORS Issue with Demo

### ISSUE THREAD

**Issue by joncameron** [avalonmediasystem/avalon#6097]
# Description
Mat Jordan was testing Clover and reports a CORS issue with the timeliner manifest: “CORS Error on https://demo.avalonmediasystem.org/timelines/59/manifest.json -- Reason: CORS header ‘Access-Control-Allow-Origin’ missing.” It's possible that timeline manifests may have never been working with CORS on the demo site.  

# Examples
https://samvera-labs.github.io/clover-iiif/docs/viewer/demo?iiif-content=https://demo.avalonmediasystem.org/timelines/59/manifest.json

Looks like CORS error with non-timeliner manifests coming from demo site, as well: https://samvera-labs.github.io/clover-iiif/docs/viewer/demo?iiif-content=https%3A%2F%2Fdemo.avalonmediasystem.org%2Fmedia_objects%2Fpk02cb02n%2Fmanifest.json

# Done Looks Like
- [x] Manifests on the Demo instance are able to be requested successfully from other sites (CORS)

**Comment by elynema** [comment]
Just confirming that this is causing issues across multiple other IIIF AV players, but not in Ramp?

**Comment by joncameron** [comment]
This shouldn't affect the Ramp demo site since it has the same *.avalonmediasystem.org parent address, but it's definitely affecting players on other sites as shown in the examples.

The errors for the media objects are very noticeable in Safari in the browser console. There seem to be a lot of resources from Demo that are getting denied due to CORS, mostly media object assets.

**Comment by cjcolvar** [comment]
This ended up being two issues with the Rack::Cors configuration:
- Missing configuration for supplemental files or other active_storage routes
- Timeliner and playlist manifest routes were too restrictive and required `.json` extensions
These should be resolved with #6103 and have been patched on the demo server until a new version of avalon is deployed there.

There is still a CORS issue reported for the timeliner manifest in clover but I think that is an issue with the IIIF auth flow and not a real CORS issue.

**Comment by joncameron** [comment]
The media object manifest is working as expected when I try the demo site example in the issue. The Timeliner manifest seems to somewhat load but isn't functional. 

@cjcolvar I still see one CORS error in the network for `GET https://demo.avalonmediasystem.org/users/sign_in?login_popup=1/info.json` at https://samvera-labs.github.io/clover-iiif/docs/viewer/demo?iiif-content=https://demo.avalonmediasystem.org/timelines/59/manifest.json. Is that expected or one that also needs to be added?

**Comment by cjcolvar** [comment]
@joncameron I think that one CORS error might be related to clover not handling auth flow correctly.  I don't see why it would be trying to fetch the sign_in in the background instead of popping up a new tab or window which should make it first order instead of cross domain.
